sudo: false
dist: trusty
language: c
compiler:
  - clang
  - gcc
install:
  - git clone https://github.com/hivesolutions/viriatum.git
  - pushd viriatum
  - ./autogen.sh && CFLAGS="-O2 -fPIC" ./configure --prefix=/usr && make && sudo make install
  - popd
script: make all
