sudo: false
dist: trusty
language: c
compiler:
  - clang
  - gcc
install:
  - git clone https://github.com/hivesolutions/viriatum.git
  - pushd viriatum
  - ./autogen.sh && ./configure --prefix=/usr && make && sudo PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin make install
  - popd
script: make all
