sudo: false
dist: trusty
language: c
compiler:
  - clang
  - gcc
install:
  - git clone https://github.com/hivesolutions/viriatum.git
  - pushd viriatum
  - ./autogen.sh && ./configure --prefix=/usr && make && sudo env "PATH=$PATH" make install
  - popd
script: make all
