sudo: false
dist: trusty
language: c
compiler:
  - clang
  - gcc
install:
  - git clone https://github.com/hivesolutions/viriatum.git
  - cd viriatum && ./autogen.sh && ./configure && make && sudo make install
script: make all
