name: Main Workflow
on: [push]
jobs:
  build-gcc:
    name: Build
    strategy:
      matrix:
        gcc-version: [5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    container: gcc:${{ matrix.gcc-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Viriatum
        run: |
          git clone https://github.com/hivesolutions/viriatum.git
          cd viriatum
          ./autogen.sh
          ./configure --prefix=/usr
          make
          make install
      - name: Build Mingus
        run: |
          make all
      - name: Build & Run Examples
        run: |
          make examples.run
